[2025-05-26T15:10:57.040+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2025-05-26T06:54:00+00:00 [queued]>
[2025-05-26T15:10:57.046+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2025-05-26T06:54:00+00:00 [queued]>
[2025-05-26T15:10:57.048+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:10:57.071+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task1> on 2025-05-26 06:54:00+00:00
[2025-05-26T15:10:57.076+0000] {standard_task_runner.py:57} INFO - Started process 4064 to run task
[2025-05-26T15:10:57.083+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2025-05-26T06:54:00+00:00', '--job-id', '400', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmprda4zy0r']
[2025-05-26T15:10:57.086+0000] {standard_task_runner.py:85} INFO - Job 400: Subtask task1
[2025-05-26T15:10:57.103+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:10:57.141+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task1 scheduled__2025-05-26T06:54:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:10:57.217+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T06:54:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T06:54:00+00:00'
[2025-05-26T15:10:57.218+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:10:57.219+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the first task!']
[2025-05-26T15:10:57.227+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:10:57.228+0000] {subprocess.py:93} INFO - Hello world, this is the first task!
[2025-05-26T15:10:57.229+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:10:57.252+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, execution_date=20250526T065400, start_date=20250526T151057, end_date=20250526T151057
[2025-05-26T15:10:57.301+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:10:57.331+0000] {taskinstance.py:2776} INFO - 2 downstream tasks scheduled from follow-on schedule check
