[2025-05-26T15:11:41.933+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2025-05-26T13:30:00+00:00 [queued]>
[2025-05-26T15:11:41.952+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dag.task1 scheduled__2025-05-26T13:30:00+00:00 [queued]>
[2025-05-26T15:11:41.953+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 6
[2025-05-26T15:11:41.975+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): task1> on 2025-05-26 13:30:00+00:00
[2025-05-26T15:11:41.986+0000] {standard_task_runner.py:57} INFO - Started process 5285 to run task
[2025-05-26T15:11:41.992+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dag', 'task1', 'scheduled__2025-05-26T13:30:00+00:00', '--job-id', '797', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpc7690xf1']
[2025-05-26T15:11:41.999+0000] {standard_task_runner.py:85} INFO - Job 797: Subtask task1
[2025-05-26T15:11:42.012+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-26T15:11:42.042+0000] {task_command.py:415} INFO - Running <TaskInstance: first_dag.task1 scheduled__2025-05-26T13:30:00+00:00 [running]> on host 4ef62d544527
[2025-05-26T15:11:42.119+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sirtaf' AIRFLOW_CTX_DAG_ID='first_dag' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-26T13:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-26T13:30:00+00:00'
[2025-05-26T15:11:42.120+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-26T15:11:42.121+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo Hello world, this is the first task!']
[2025-05-26T15:11:42.130+0000] {subprocess.py:86} INFO - Output:
[2025-05-26T15:11:42.132+0000] {subprocess.py:93} INFO - Hello world, this is the first task!
[2025-05-26T15:11:42.133+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-05-26T15:11:42.172+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=task1, execution_date=20250526T133000, start_date=20250526T151141, end_date=20250526T151142
[2025-05-26T15:11:42.225+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-05-26T15:11:42.291+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
